<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ThinkITAM</RootNamespace>
    <AssemblyName>ThinkITAM.Avalonia</AssemblyName>
    <ApplicationIcon>ThinkItamlogo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
    <PackageReference Include="Avalonia.Remote.Protocol" Version="12.0.4" />
    <PackageReference Include="Avalonia.Skia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
    <!-- <PackageReference Include="Avalonia.Diagnostics" Version="11.3.17" /> -->
    <PackageReference Include="Material.Icons.Avalonia" Version="3.0.2" />
    <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
    <PackageReference Include="NodifyAvalonia" Version="6.6.0" />
    <PackageReference Include="Markdown.Avalonia" Version="11.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThinkITAM.Database\ThinkITAM.Database.csproj" />
    <ProjectReference Include="..\ThinkITAM.Shared\ThinkITAM.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\**" />
    <AvaloniaResource Include="Language\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Bold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Light.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Medium.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Image\Background.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
