<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>False</UseWindowsForms>
    <ApplicationIcon>ThinkItamlogo.ico</ApplicationIcon>
    <Platforms>AnyCPU;x64;ARM32;ARM64;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Document\ThinkITAM使用手册.pdf" />
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC_Bold.ttf" />
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC_Light.ttf" />
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC_Medium.ttf" />
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC_Regular.ttf" />
    <None Remove="Resources\Image\AliPay.png" />
    <None Remove="Resources\Image\Background.png" />
    <None Remove="Resources\Image\QR.png" />
    <None Remove="Resources\Image\WeChat.png" />
    <None Remove="Resources\Logo\Logo150x150.png" />
    <None Remove="Resources\Logo\Logo44x44.png" />
    <None Remove="Resources\Template\AssetTemplate.xlsx" />
    <None Remove="Resources\Template\UserInfoTemplate.xlsx" />
    <None Remove="Resources\UpdateInfo\MarkdownHelp.md" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Document\ThinkITAM使用手册.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Template\AssetTemplate.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Template\UserInfoTemplate.xlsx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\UpdateInfo\MarkdownHelp.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="ThinkItamlogo.ico" />
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Bold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Light.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Medium.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\UpdateInfo\UpdateInfo.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Sounds\CopySounds.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AForge.Video" Version="2.2.5" />
    <PackageReference Include="AForge.Video.DirectShow" Version="2.2.5" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Dapper.Contrib" Version="2.0.78" />
    <PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
    <PackageReference Include="MacAddressVendorLookup" Version="1.1.13" />
    <PackageReference Include="Markdig.Wpf" Version="0.5.0.1" />
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.9" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Nmap.NET" Version="1.0.4" />
    <PackageReference Include="Nodify" Version="7.1.0" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="System.Management" Version="9.0.9" />
    <PackageReference Include="ZXing.Net" Version="0.16.10" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" Version="0.16.21" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Windows\Computer\ComputerEditWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Windows\PortPanel\PortPanelEditWindow.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Functions\Database\" />
    <Folder Include="UserControls\Menus\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Image\AliPay.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Image\Background.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Image\QR.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Image\WeChat.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Logo\Logo310x150.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Logo\Logo150x150.png" />
    <Resource Include="Resources\Logo\Logo44x44.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
