<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC_Bold.ttf" />
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC_Light.ttf" />
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC_Medium.ttf" />
    <None Remove="Resources\Fonts\HarmonyOS_Sans_SC_Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Bold.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Light.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Medium.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\HarmonyOS_Sans_SC_Regular.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AForge.Video" Version="2.2.5" />
    <PackageReference Include="AForge.Video.DirectShow" Version="2.2.5" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
    <PackageReference Include="MacAddressVendorLookup" Version="1.1.13" />
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.4" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Nodify" Version="7.0.3" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="System.Management" Version="9.0.4" />
    <PackageReference Include="ZXing.Net" Version="0.16.10" />
    <PackageReference Include="ZXing.Net.Bindings.SkiaSharp" Version="0.16.21" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>
